### ISSUE TITLE
import_dependencies not a cli option (?)

### ISSUE THREAD

**Issue by majidaldo** [gtfierro/ontoenv#12]
https://github.com/majidaldo/ontoenv/blob/695b97dbd69238b9d64adaeb3dc3c3bc5b7655bc/ontoenv/cli.py#L65

wouldn't this be the main function from the cli?

**Comment by gtfierro** [comment]
Can you please be more specific with your question?

**Comment by majidaldo** [comment]
> Can you please be more specific with your question?

https://github.com/gtfierro/ontoenv/blob/main/ontoenv/cli.py 

there is no use of `import_dependencies` from the cli.

**Comment by gtfierro** [comment]
It doesn't show up in the CLI because you pointed to a commit on your fork; this code is not part of the main branch and isn't in any release. Would you want the `import_deps` function included? If you submit a PR I can include it in a future release

**Comment by gtfierro** [comment]
Available in 0.3.8a6
