### ISSUE TITLE
upgrade to rdflib 7

### ISSUE THREAD

**Issue by majidaldo** [gtfierro/ontoenv#16]
https://github.com/gtfierro/ontoenv/blob/c20a1c741c879717ea2c4109e5c322445885d70c/pyproject.toml#L10

seems [safe](https://rdflib.readthedocs.io/en/stable/upgrade6to7.html). seems to work fine when it  had rdflib7.

**Comment by gtfierro** [comment]
PRs are welcome!

**Comment by gtfierro** [comment]
Also available in 0.3.8a6
