### ISSUE TITLE
also remove owl:imports?

### ISSUE THREAD

**Issue by majidaldo** [gtfierro/ontoenv#18]
https://github.com/gtfierro/ontoenv/blob/c20a1c741c879717ea2c4109e5c322445885d70c/ontoenv/__init__.py#L270

Does it make sense to also remove owl:imports here so that another processor doesn't also process the imports ([including ontoenv ittself](https://github.com/gtfierro/ontoenv/issues/13))?

**Comment by gtfierro** [comment]
Can you be more specific? Do you mean removing them as part of importing the dependencies? Ontoenv knows which graphs it has visited so I don't think we want to remove the `owl:imports`

**Comment by majidaldo** [comment]
> Can you be more specific? Do you mean removing them as part of importing the dependencies? Ontoenv knows which graphs it has visited so I don't think we want to remove the `owl:imports`

Removing the triples  (s, owl:imports, o). Since ontoenv did the importation process, it doesn't make sense for potentially another program (like shacl  ) to also do it.

**Comment by gtfierro** [comment]
Ok, I see what you mean here. I've added this as a configurable option, but it's on by default. Available in 0.3.9a1
