### ISSUE TITLE
exceptions not raising in finding ontologies (?)

### ISSUE THREAD

**Issue by majidaldo** [gtfierro/ontoenv#2]
https://github.com/gtfierro/ontoenv/blob/b1ed559f8804dffe68708efdc580407bb2ffd707/ontoenv/__init__.py#L167

https://github.com/gtfierro/ontoenv/blob/b1ed559f8804dffe68708efdc580407bb2ffd707/ontoenv/__init__.py#L143

is there a reason why these are not `raise`ing? in cli use the exit code is 0.

**Comment by gtfierro** [comment]
I didn't want the inability to find an ontology impede the import process. During development, there are a number of URLs that get thrown around that don't have a formal ontology definition either locally or on the web. One possible solution to this is to have a "strict" mode that throws exceptions when these cases are hit -- would that be helpful?

**Comment by majidaldo** [comment]
> I didn't want the inability to find an ontology impede the import process. During development, there are a number of URLs that get thrown around that don't have a formal ontology definition either locally or on the web. One possible solution to this is to have a "strict" mode that throws exceptions when these cases are hit -- would that be helpful?

oh ok. that would actually help to check when you go 'production'.

**Comment by gtfierro** [comment]
There's a new strict flag `-s` available in `ontoenv==0.3.3`; let me know if it works as you expect!

**Comment by majidaldo** [comment]
works as expected. thanks.

**Comment by majidaldo** [comment]
[                logging.error(f"Could not load {uri} (no definition found)")](https://github.com/gtfierro/ontoenv/blob/1f7663205a9825539c738dbae201c05b00edf696/ontoenv/__init__.py#L246)
'strict' treatment is not applied here though.
