### ISSUE TITLE
fix PIL/Pillow dep issue

### ISSUE THREAD

**Issue by majidaldo** [gtfierro/ontoenv#6]
from a clean slate, poetry installed mpl with an incompatible PIL. updating fixed it.

https://github.com/majidaldo/ontoenv/commit/07014d0421341976c72d73ed06ee180d2dc5ca8b

maybe have mpl as an optional install if the user wants graphics. mpl brings the (complicated) scientific stack with it.

(you might even be able to knock out networkx but that's another discussion)

**Comment by gtfierro** [comment]
Python 3.7 is EOL in ~5 months but I'm not sure I want to remove support for it yet. I'd rather make mpl optional. Can you check that the linked PR #9 works for you?
